"""Init reports tables

Revision ID: e0ab732bc6e3
Revises: 
Create Date: 2026-04-15 22:06:06.942622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0ab732bc6e3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farms_id'), 'farms', ['id'], unique=False)
    op.create_table('report_config',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('report_category', sa.String(), nullable=True),
    sa.Column('group_by', sa.String(), nullable=True),
    sa.Column('date_range_type', sa.String(), nullable=True),
    sa.Column('date_from', sa.DateTime(), nullable=True),
    sa.Column('date_to', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_report_config_report_id'), 'report_config', ['report_id'], unique=False)
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_areas_id'), 'areas', ['id'], unique=False)
    op.create_table('report_dataset',
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('source_table', sa.String(), nullable=False),
    sa.Column('sensor_metric_code', sa.String(), nullable=True),
    sa.Column('event_category', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('alias', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['report_config.report_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id')
    )
    op.create_index(op.f('ix_report_dataset_dataset_id'), 'report_dataset', ['dataset_id'], unique=False)
    op.create_table('report_instance',
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('date_from', sa.DateTime(), nullable=True),
    sa.Column('date_to', sa.DateTime(), nullable=True),
    sa.Column('result_summary', sa.String(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('generated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['report_config.report_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('instance_id')
    )
    op.create_index(op.f('ix_report_instance_instance_id'), 'report_instance', ['instance_id'], unique=False)
    op.create_table('alert_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_logs_id'), 'alert_logs', ['id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_table('harvest_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('crop_type', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('harvested_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_harvest_logs_id'), 'harvest_logs', ['id'], unique=False)
    op.create_table('irrigation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('water_amount', sa.Float(), nullable=True),
    sa.Column('irrigated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_irrigation_logs_id'), 'irrigation_logs', ['id'], unique=False)
    op.create_table('report_export',
    sa.Column('export_id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('exported_at', sa.DateTime(), nullable=True),
    sa.Column('exported_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['report_instance.instance_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('export_id')
    )
    op.create_index(op.f('ix_report_export_export_id'), 'report_export', ['export_id'], unique=False)
    op.create_table('report_filter',
    sa.Column('filter_id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('filter_type', sa.String(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('operator', sa.String(), nullable=False),
    sa.Column('value_from', sa.String(), nullable=True),
    sa.Column('value_to', sa.String(), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['report_dataset.dataset_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['report_config.report_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('filter_id')
    )
    op.create_index(op.f('ix_report_filter_filter_id'), 'report_filter', ['filter_id'], unique=False)
    op.create_table('report_metric',
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('metric_code', sa.String(), nullable=False),
    sa.Column('aggregation', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('color_hex', sa.String(), nullable=True),
    sa.Column('metric_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['report_dataset.dataset_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['report_config.report_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('metric_id')
    )
    op.create_index(op.f('ix_report_metric_metric_id'), 'report_metric', ['metric_id'], unique=False)
    op.create_table('report_layout',
    sa.Column('layout_id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('metric_id', sa.Integer(), nullable=True),
    sa.Column('chart_type', sa.String(), nullable=True),
    sa.Column('widget_x', sa.Integer(), nullable=True),
    sa.Column('widget_y', sa.Integer(), nullable=True),
    sa.Column('widget_w', sa.Integer(), nullable=True),
    sa.Column('widget_h', sa.Integer(), nullable=True),
    sa.Column('x_axis', sa.String(), nullable=True),
    sa.Column('y_axis', sa.String(), nullable=True),
    sa.Column('show_legend', sa.Integer(), nullable=True),
    sa.Column('show_tooltip', sa.Integer(), nullable=True),
    sa.Column('show_data_label', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['metric_id'], ['report_metric.metric_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['report_config.report_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('layout_id')
    )
    op.create_index(op.f('ix_report_layout_layout_id'), 'report_layout', ['layout_id'], unique=False)
    op.create_table('report_metric_condition',
    sa.Column('condition_id', sa.Integer(), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=True),
    sa.Column('condition_order', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('operator', sa.String(), nullable=True),
    sa.Column('value_from', sa.Float(), nullable=True),
    sa.Column('value_to', sa.Float(), nullable=True),
    sa.Column('color_hex', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['metric_id'], ['report_metric.metric_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('condition_id')
    )
    op.create_index(op.f('ix_report_metric_condition_condition_id'), 'report_metric_condition', ['condition_id'], unique=False)
    op.create_table('sensors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensors_id'), 'sensors', ['id'], unique=False)
    op.create_table('telemetry_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity_air', sa.Float(), nullable=True),
    sa.Column('humidity_soil', sa.Float(), nullable=True),
    sa.Column('light_intensity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_logs_id'), 'telemetry_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_logs_id'), table_name='telemetry_logs')
    op.drop_table('telemetry_logs')
    op.drop_index(op.f('ix_sensors_id'), table_name='sensors')
    op.drop_table('sensors')
    op.drop_index(op.f('ix_report_metric_condition_condition_id'), table_name='report_metric_condition')
    op.drop_table('report_metric_condition')
    op.drop_index(op.f('ix_report_layout_layout_id'), table_name='report_layout')
    op.drop_table('report_layout')
    op.drop_index(op.f('ix_report_metric_metric_id'), table_name='report_metric')
    op.drop_table('report_metric')
    op.drop_index(op.f('ix_report_filter_filter_id'), table_name='report_filter')
    op.drop_table('report_filter')
    op.drop_index(op.f('ix_report_export_export_id'), table_name='report_export')
    op.drop_table('report_export')
    op.drop_index(op.f('ix_irrigation_logs_id'), table_name='irrigation_logs')
    op.drop_table('irrigation_logs')
    op.drop_index(op.f('ix_harvest_logs_id'), table_name='harvest_logs')
    op.drop_table('harvest_logs')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_alert_logs_id'), table_name='alert_logs')
    op.drop_table('alert_logs')
    op.drop_index(op.f('ix_report_instance_instance_id'), table_name='report_instance')
    op.drop_table('report_instance')
    op.drop_index(op.f('ix_report_dataset_dataset_id'), table_name='report_dataset')
    op.drop_table('report_dataset')
    op.drop_index(op.f('ix_areas_id'), table_name='areas')
    op.drop_table('areas')
    op.drop_index(op.f('ix_report_config_report_id'), table_name='report_config')
    op.drop_table('report_config')
    op.drop_index(op.f('ix_farms_id'), table_name='farms')
    op.drop_table('farms')
    # ### end Alembic commands ###
